# Site settings
title: OSer916 Blog 
email: cuichaochao916@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Just For Fun! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://OSer916.github.io" # the base hostname & protocol for your site
twitter_username: OSer916
github_username: OSer916 
linkedin_url: 
facebook_url: 
flickr_url: ""

imageurl: "https://OSer916.github.io/images"

# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: rouge
